const APP_TEXTS = {
  welcomeTitle: "Welcome to Margaret",
  getStartedText: "Get Started",
  joinNowText: "Join Now",
  loginHeader: "Sign in to continue",
  registerHeader: "Create new account",
  forgotPasswordPageHeader: "Forgot Password",
  forgotPasswordHeader: "Continue using email ID",
  resetPasswordPageHeader: "Reset Password",
  resetPasswordHeader: "Enter OTP sent to your email ID",
  namePlaceholder: "Name",
  emailPlaceholder: "Email",
  phonePlaceholder: "Phone",
  passwordPlaceholder: "Password",
  otpPlaceholder: "OTP",
  newPasswordPlaceholder: "New Password",
  forgotPasswordText: "Forgot Password?",
  loginButton: "Log In",
  registerButton: "Create Account",
  forgotPasswordButton: "Send Verification Code",
  resetPasswordButton: "Submit",
  signUpText: "Don't have an account?",
  loginText: "Already have an account?",
  createAccountText: "Create New Account",
  signInText: "Sign In",
};

export default APP_TEXTS;
